#!/usr/bin/env Rscript
#' Publication-Ready Figures for Scopus Bias Study
#'
#' This script generates Figures 2-4 for the manuscript:
#' - Figure 2: Scopus coverage by field type (box plots)
#' - Figure 3: Elsevier percentage vs coverage ratio (scatterplot)
#' - Figure 4: Book percentage vs coverage ratio (scatterplot)
#'
#' NOTE: Figure 1 (University Adoption) is generated by figure_4_university_adoption.py
#'
#' Input: data/openalex_comprehensive_data.csv (600 researchers)
#' Output: figures/*.png (300 DPI, publication-ready)
#'
#' Dependencies: ggplot2, dplyr, tidyr, scales
#' Install with: Rscript install_r_dependencies.R
#'
#' Usage:
#'   Rscript scripts/R/figures_1_2_3_coverage_analysis.R
#'
#' Expected runtime: ~10 seconds
#' Expected output size: ~1.4 MB total (3 figures)

options(repos = c(CRAN = "https://cloud.r-project.org"))

# Load required packages with full namespace specification
cat("Loading required packages...\n")
suppressPackageStartupMessages({
  library(ggplot2)  # Graphics: ggplot2::ggplot, ggplot2::aes, etc.
  library(dplyr)    # Data manipulation: dplyr::filter, dplyr::mutate, etc.
  library(tidyr)    # Data tidying
  library(scales)   # Scales: scales::percent_format
})
cat("✓ Packages loaded\n\n")

# Create figures and tables directories
dir.create("figures", showWarnings = FALSE)
dir.create("tables", showWarnings = FALSE)

# Load data (n=600 sample)
cat("Loading openalex_comprehensive_data.csv...\n")
df <- read.csv("data/openalex_comprehensive_data.csv", stringsAsFactors = FALSE)
cat(sprintf("Initial rows: %d\n", nrow(df)))

# Filter to matched researchers
df <- df[df$openalex_found == TRUE | df$openalex_found == "True", ]
cat(sprintf("After openalex filter: %d\n", nrow(df)))

# Clean data: same as Python analysis
df <- df[!is.na(df$coverage_ratio) & !is.na(df$elsevier_pct) & df$coverage_ratio <= 1.5, ]

cat(sprintf("✓ Loaded %d researchers (after cleaning)\n\n", nrow(df)))

# Publication theme
theme_pub <- theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0),
    plot.subtitle = element_text(size = 12, color = "gray30"),
    axis.title = element_text(face = "bold", size = 13),
    legend.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

#' =============================================================================
#' FIGURE 2: Scopus Coverage by Field Type
#' =============================================================================
#' Shows distribution of coverage ratios across three field types using
#' box plots with overlaid data points.
#'
#' Key finding: Book-heavy fields show ~31% median coverage vs ~71% for
#' journal-heavy fields (39.9 percentage point difference, p<0.001)

cat("Creating Figure 2: Coverage by field type...\n")

# Create factor for field types with human-readable labels
df$field_label <- factor(df$field_type,
                         levels = c("book_heavy", "mixed", "journal_heavy"),
                         labels = c("Book-heavy", "Mixed", "Journal-heavy"))

# Generate box plot with data points
# Uses: ggplot2::ggplot(), ggplot2::aes(), ggplot2::geom_boxplot(),
#       ggplot2::geom_jitter(), ggplot2::geom_hline(),
#       ggplot2::scale_y_continuous(), ggplot2::scale_fill_manual(),
#       ggplot2::labs(), ggplot2::theme()
fig1 <- ggplot(df, aes(x = field_label, y = coverage_ratio, fill = field_label)) +
  geom_boxplot(alpha = 0.7) +  # Box plots showing quartiles
  geom_jitter(width = 0.2, alpha = 0.3) +  # Individual data points
  geom_hline(yintercept = 1.0, linetype = "dashed", color = "red") +  # 100% reference line
  scale_y_continuous(labels = percent_format()) +  # Format y-axis as percentages
  scale_fill_manual(values = c("#D55E00", "#E69F00", "#0072B2")) +  # Colorblind-safe palette
  labs(title = "Scopus Coverage by Field Type",
       subtitle = "Ratio of Scopus publications to OpenAlex publications",
       x = "", y = "Coverage Ratio") +
  theme_pub + theme(legend.position = "none")

# Save as PNG: 10×7 inches, 300 DPI (publication quality)
# Uses: ggplot2::ggsave()
ggsave("figures/Figure2_Coverage_by_Field.png", fig1, width = 10, height = 7, dpi = 300)
ggsave("figures/Figure2_Coverage_by_Field.pdf", fig1, width = 10, height = 7)
cat("✓ Figure 2 saved (PNG + PDF)\n\n")

# FIGURE 3: Elsevier % vs Coverage
cat("Creating Figure 3: Publisher bias...\n")
correlation <- cor(df$elsevier_pct, df$coverage_ratio, use = "complete.obs")

fig2 <- ggplot(df, aes(x = elsevier_pct, y = coverage_ratio, color = field_label)) +
  geom_point(alpha = 0.6, size = 2.5) +
  geom_smooth(method = "lm", se = TRUE, color = "black", linetype = "dashed") +
  geom_hline(yintercept = 1.0, linetype = "dotted", color = "red") +
  scale_x_continuous(labels = percent_format(scale = 1)) +
  scale_y_continuous(labels = percent_format()) +
  scale_color_manual(values = c("#D55E00", "#E69F00", "#0072B2"), name = "Field Type") +
  annotate("text", x = max(df$elsevier_pct) * 0.7, y = 1.4,
           label = sprintf("r = %.3f", correlation), size = 6, fontface = "bold") +
  labs(title = "Publisher Bias: Elsevier % vs Scopus Coverage",
       subtitle = "Does publishing in Elsevier journals predict better Scopus coverage?",
       x = "% Publications in Elsevier Journals", y = "Coverage Ratio") +
  theme_pub

ggsave("figures/Figure3_Elsevier_vs_Coverage.png", fig2, width = 10, height = 7, dpi = 300)
ggsave("figures/Figure3_Elsevier_vs_Coverage.pdf", fig2, width = 10, height = 7)
cat("✓ Figure 3 saved (PNG + PDF)\n\n")

# FIGURE 4: Book % vs Coverage
cat("Creating Figure 4: Book bias...\n")
correlation_books <- cor(df$books_pct, df$coverage_ratio, use = "complete.obs")

fig3 <- ggplot(df, aes(x = books_pct, y = coverage_ratio, color = field_label)) +
  geom_point(alpha = 0.6, size = 2.5) +
  geom_smooth(method = "lm", se = TRUE, color = "black", linetype = "dashed") +
  geom_hline(yintercept = 1.0, linetype = "dotted", color = "red") +
  scale_x_continuous(labels = percent_format(scale = 1)) +
  scale_y_continuous(labels = percent_format()) +
  scale_color_manual(values = c("#D55E00", "#E69F00", "#0072B2"), name = "Field Type") +
  annotate("text", x = max(df$books_pct) * 0.7, y = 1.4,
           label = sprintf("r = %.3f", correlation_books), size = 6, fontface = "bold") +
  labs(title = "Book Bias: Book % vs Scopus Coverage",
       subtitle = "Do researchers with more books/chapters have worse Scopus coverage?",
       x = "% Publications that are Books/Chapters", y = "Coverage Ratio") +
  theme_pub

ggsave("figures/Figure4_Books_vs_Coverage.png", fig3, width = 10, height = 7, dpi = 300)
ggsave("figures/Figure4_Books_vs_Coverage.pdf", fig3, width = 10, height = 7)
cat("✓ Figure 4 saved (PNG + PDF)\n\n")

# Summary statistics
cat("Creating summary table...\n")
summary_stats <- df %>%
  group_by(field_type) %>%
  summarise(
    N = n(),
    Coverage_Median = sprintf("%.1f%%", median(coverage_ratio) * 100),
    Elsevier_Median = sprintf("%.1f%%", median(elsevier_pct)),
    Books_Median = sprintf("%.1f%%", median(books_pct))
  )

write.csv(summary_stats, "tables/Table1_Summary.csv", row.names = FALSE)
cat("✓ Summary table saved\n\n")

cat("=" , rep("=", 70), "=\n", sep = "")
cat("FIGURE GENERATION COMPLETE\n")
cat("=" , rep("=", 70), "=\n\n", sep = "")
cat("Figures saved to: figures/\n")
cat("  • Figure 2: Coverage by field type\n")
cat("  • Figure 3: Elsevier % vs Coverage\n")
cat("  • Figure 4: Book % vs Coverage\n")
cat("  • Table 1: Summary statistics\n\n")
